travis:
  secure:
    BINSTAR_TOKEN: SzeNleRv3bxoUmnsSa2Hchm95n7wnanQLG6Ng1FW2NE9KhHvbLt6U4waD1HtWNY/mKdKpG/TVbBnkSPCKi35Ra+pHnPya1C95w8pHKrFf8mIfBLU8XKTIaxoP55cHCO9oFcpfV83kh39QyNiJSGJNfeKprknGyT5FdhDyUkuPH7hQbnHGuXGc0/UoSsGmzJSdx6hv+jg9dgSdBHJ7sKFYIhjreqabO9mX2NXkG4+F5ADki7o2/IwTEGU7oktlDhJOqcUq6CJCIpnBZXFL2G5sN6Y5yd9axbSdN1NkZ0fTOIEkCTmZnpGTL8UKHtrSIUmHVCfPBZBazfXrGDfOCSDamMhyrmKTR8QyDjkscivCqMQ57Ub9+ZEJqNUcbivDftEiV4GhqOR2B1RrIWQ75M+TFN+0OzDmqsSjbGZGt9GqFW5mUJunOFIarE/rcueMclTp6HfznH7dOCvfOPoMuoK6bt7WsmmXYsyeDxmTpgsGYQhuFbQqRJKdKaN/5rPAAoDOZKagZz5b2WdkDNT4JY2Hw44jqTBydBosLR/CXBlxI3Jm45QOkCKTHltQGLGFQekGYJEfwnECNd5ydm2NXxtYNEl04OifWhN9gb/hUpZ/e1+VbM0fS7KCNaqy8rneyFmLHhNH7tILs2Aez9bheQC0k3qGHir1xSt5jaJ/hUYetQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
