travis:
  secure:
    BINSTAR_TOKEN: Wc/yPhiEp6DHgd3fbO33kKze69BW+TdF+42+p+Mx+ZyccrkJDC9uo7t5GAMcAQT9W2mYpMIH+rwU52DtTYV2vhBQoBHZvb/5NhgA17q4dOpYFByHp1IirVzwG49mxPepBEiJELXu+Rxoob5sftOObgbj44EDoFVDGOllkDmkK3surd+HcZ+pqHVC8d+ufLhrDSpTeXIn6RZKPeoHXDfLSpnKUxzYGI5Srq1iklmiMaenvCLeREVbKoxpFNgRydd/nuDF3hx5TOhgKOltz+3bhZFJCVgx/gaLZ0yHgV4jx9ala3o6NOgDWEpwZ7SgY8Qqt2Lwu+HPRHGDzoyR2EVaJvhDcmArGKBMRa9Jj90V4c6Gg1fWllL6xT/qbJBYN2REu/KcHSkX87pNKkS2AGFX3bKvBd9AVW0h3+uzoEgoNzepB94oRa8Vk5BKOL/3naNQ/y+kxXPupZ9sj2HE0aNa/nbp2vpSyjfZi6kFFxc5NUX27JxGGug5BeEfYuhyxB5ambI1FwrMer/S64dB6OlW0bWwrj/OV1+47/fuXNeIcXCGNmE6u1Zv89w/sqtO99mcwJqpPEcX+PcpLRVYp8z+MIl1je0oFPZg1Bt3Qx6YgxfaWufytIferOVXPDR3bzspw+GADYmdn0dMwMFkubONfjXvc+iIRS/6m6FjE5GnK/E=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
